---
title: "Lab 7"
author: Alina Sequeira
date: 11-10-20
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
## ----style, echo=FALSE, message=FALSE, warning=FALSE, results="asis"----------
library("BiocStyle")
library("knitr")
library("rmarkdown")
```
```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("rnaseqGene")

# I also needed to install the following on my computer 
# (You will realize this if you get an error message that the corresponding library will not load)

BiocManager::install("airway")
BiocManager::install("tximeta")
BiocManager::install("DESeq2")
BiocManager::install("Gviz")
BiocManager::install("sva")
BiocManager::install("RUVSeq")
BiocManager::install("fission")
```
```{r}
browseVignettes("rnaseqGene")
```
```{r}
## store to directory
dir <- system.file("extdata", package="airway", mustWork=TRUE)

## files in directory
list.files(dir)
```
```{r}
list.files(file.path(dir, "quants"))
```
```{r}
## Load CSB file
csvfile <- file.path(dir, "sample_table.csv")
coldata <- read.csv(csvfile, row.names=1, stringsAsFactors=FALSE)
coldata
```
```{r}
## make coldata - column creation
coldata <- coldata[1:2,]
coldata$names <- coldata$Run
coldata$files <- file.path(dir, "quants", coldata$names, "quant.sf.gz")
file.exists(coldata$files)
```
```{r}
browseVignettes("tximeta")
```
```{r}
library("tximeta")
se <- tximeta(coldata)
```


```{r}
## Summarized Experiment, 
echo=FALSE
par(mar=c(0,0,0,0))
plot(1,1,xlim=c(0,100),ylim=c(0,100),bty="n",
     type="n",xlab="",ylab="",xaxt="n",yaxt="n")
polygon(c(45,90,90,45),c(5,5,70,70),col="pink",border=NA)
polygon(c(45,90,90,45),c(68,68,70,70),col="pink3",border=NA)
text(67.5,40,"assay(s)")
text(67.5,35,'e.g. "counts", ...')
polygon(c(10,40,40,10),c(5,5,70,70),col="skyblue",border=NA)
polygon(c(10,40,40,10),c(68,68,70,70),col="skyblue3",border=NA)
text(25,40,"rowRanges")
polygon(c(45,90,90,45),c(75,75,95,95),col="palegreen",border=NA)
polygon(c(45,47,47,45),c(75,75,95,95),col="palegreen3",border=NA)
text(67.5,85,"colData")
```
```{r}
## Look se
dim(se)
```
```{r}
head(rownames(se))
```
```{r}
edb <- retrieveDb(se)
```
```{r}
suppressPackageStartupMessages(library(SummarizedExperiment))
colData(se)
```
```{r}
assayNames(se)
```
```{r}
rowRanges(se)
```
```{r}
seqinfo(se)
```
```{r}
se.exons <- addExons(se)
```
```{r}
rowRanges(se.exons)[[1]]
```

```{r}
gse <- summarizeToGene(se)
```
```{r}
## Check dimensions
dim(gse)
```
```{r}
head(rownames(gse))
```

```{r}
rowRanges(gse)
```
```{r}
## Look sequence info
seqinfo(rowRanges(gse))
```
```{r}
## coldata gse
colData(gse)
```
```{r}
## Start from count matrices
countdata <- round(assays(gse)[["counts"]])
head(countdata, 3)
```
```{r}
gse$donor
```
```{r}
gse$condition
```
```{r}
gse$cell <- gse$donor
gse$dex <- gse$condition


levels(gse$dex)

```




